---
# tasks file for budgie
- name: Install budgie
  package:
    name:
      - budgie
      - sddm
    state: present
  become: true

- name: Enable sddm
  service:
    name: sddm
    enabled: true
  become: true
