---
# tasks file for create_directories
#- name: Check if directories exist
#  stat:
#    path: "{{ item }}"
#  loop: "{{ directories }}"
#  register: directory_stats

#- name: "Creating multiple folders without disturbing previous permissions"
#  file:
#    path: "{{item}}"
#    state: directory
#    mode: 0755
#  when: item.stat.exists == false
#  loop: "{{ directory_stats.results }}"

- name: "Creating multiple folders without disturbing previous permissions"
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  loop: "{{ directories }}"
