---
# tasks file for git_config
- name: Add name to git config
  git_config:
    name: user.name
    scope: global
    value: "{{ default_name }}"

- name: Add email to git config
  git_config:
    name: user.email
    scope: global
    value: "{{ default_email }}"

- name: Add name to git config
  git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ default_branch }}"
