---
# tasks file for i3wm
#- name: Install xorg
#  include_role:
#    name: xorg
#
- name: Install i3wm packages
  package:
    name:
      - sddm
      - i3-wm
      - i3status
      - dmenu
      - perl-anyevent-i3
  become: true

- name: Check if directories exist
  stat:
    path: "{{ item }}"
  with_items: "{{ directories }}"
  register: directory_stats

- name: "Creating i3wm directories"
  file:
    path: "{{item.item}}"
    state: directory
    mode: 0755
  when: item.stat.exists == false
  with_items: "{{ directory_stats.results }}"

- name: Enable sddm
  service:
    name: sddm
    enabled: true
  become: true
