---
# tasks file for lightdm
- name: Install lightdm and related packages
  package:
    name:
      - lightdm
      - lightdm-gtk-greeter
  state: present
  become: true

- name: Enable lightdm
  service:
    name: lightdm
    enabled: true
