---
# tasks file for awesome
- name: Install awesome
  package:
    name:
      - awesome
      - sddm
    state: present
  become: true

- name: Enable sddm
  service:
    name: sddm
    enabled: true
  become: true
